# Generated by Django 5.2.3 on 2025-07-18 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_types', to='todo_app.task', verbose_name='Задача')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_tasks', to='todo_app.type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Типы и Задачи',
                'verbose_name_plural': 'Типы и Задачи',
                'db_table': 'task_types',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ManyToManyField(related_name='tasks', through='todo_app.TaskType', through_fields=('task', 'type'), to='todo_app.type', verbose_name='Типы'),
        ),
    ]
